services:
  db:
    image: mysql:8.0
    container_name: todo-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Contraseña para el usuario 'root'
      MYSQL_DATABASE: todo_db # Nombre de la base de datos
      MYSQL_USER: user # Nuevo usuario para la aplicacion
      MYSQL_PASSWORD: password # Contraseña para el nuevo usuario
    ports:
      - "3306:3306" # Mapea el puerto del contenedor al puerto local
    volumes:
      - db_data:/var/lib/mysql # Persistencia de datos para que no se pierdan al detener el contenedor
      - ./backend/my.cnf:/etc/mysql/conf.d/my.cnf # Configuracion personalizada de MySQL
      - ./backend/db_init.sql:/docker-entrypoint-initdb.d/init.sql # Script para inicializar la DB
    networks:
      - todo-app-network

volumes:
  db_data:

networks:
  todo-app-network:
    driver: bridge